# Generated by Django 2.2.6 on 2020-06-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajedechat',
            old_name='Mensaje',
            new_name='mensaje',
        ),
    ]
