# Generated by Django 2.2.6 on 2020-06-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
