# Generated by Django 2.2.6 on 2020-06-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_auto_20200602_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='dislike',
            options={'verbose_name': 'Dislike', 'verbose_name_plural': 'Dislikes'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-id'], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipopublicacion',
            options={'verbose_name': 'Tipo de Publicacion', 'verbose_name_plural': 'Tipos de Publicacion'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(verbose_name='Comentario Realizado'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Comentario Activo/Comentario Eliminado'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='archivo',
            field=models.FileField(blank=True, default='', null=True, upload_to='archivo_publicacion/', verbose_name='Tipo de Archivo'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Publicacion Activa/Publicacion Eliminada'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='texto_publicacion',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de Publicacion'),
        ),
        migrations.AlterField(
            model_name='tipopublicacion',
            name='tipo_publicacion',
            field=models.CharField(max_length=50, verbose_name='Tipo de Publicacion'),
        ),
    ]
