# Generated by Django 2.2.6 on 2020-05-15 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('foto_perfil', models.ImageField(max_length=200, null=True, upload_to='perfil/', verbose_name='Foto de Perfil')),
                ('universidad', models.CharField(blank=True, default='Sin registro', max_length=150, null=True, verbose_name='Universidad')),
                ('carrera', models.CharField(blank=True, default='Sin registro', max_length=150, null=True, verbose_name='Carrera')),
                ('activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(default='Prefiero no decir', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Sin Datos', max_length=100, verbose_name='Tipo de Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='InfoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(blank=True, default='No hay datos', max_length=150, null=True)),
                ('situacion_sentimental', models.CharField(default='No hay datos', max_length=150, null=True)),
                ('descripcion_breve', models.CharField(default='No hay datos', max_length=150, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Genero'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuario.TipoUsuario'),
        ),
    ]
