# Generated by Django 2.2.6 on 2020-05-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200518_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo_electronico',
            new_name='email',
        ),
    ]
