# Generated by Django 2.2.6 on 2020-05-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20200519_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.TipoUsuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.Genero'),
        ),
    ]
