# Generated by Django 2.2.6 on 2020-05-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200521_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='foto_perfil/avatar.png', max_length=200, null=True, upload_to='foto_perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
