# Generated by Django 2.2.6 on 2020-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200521_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(blank=True, default='Prefiero no decir', max_length=15, null=True),
        ),
    ]
