# Generated by Django 2.2.6 on 2020-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20200524_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(default='Prefiero no decir', max_length=15),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(blank=True, default='Sin Datos', max_length=100, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
