# Generated by Django 2.2.6 on 2020-05-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20200524_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='activo',
            new_name='is_active',
        ),
    ]
